### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by suissemaxx** [mereldawu/ipyhealth#1]
No issue at all – I just wanted to say thanks for making your code available. 

Very cool. Works like a charm. 👍

**Comment by mereldawu** [comment]
Sure, no problem! 
Just out of interest, how big is your export file and how long did the processing take?

**Comment by suissemaxx** [comment]
- The full export is 73.5 MB zipped and 1.2 GB unzipped.
- `Export.xml  `is 778.7 MB. 
- It took around 15min to parse everything on a 2018 MacBook Pro (2.6GHz i7).
- I used the default settings and could see that all CPUs / cores were busy.

**Comment by mereldawu** [comment]
Cool, good to know it worked. Thanks!
